baseURL = "https://pdmurray.dev"
title = "Peyton Murray"
# paginate = 30
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Peyton Murray"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "2006-12-01"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowWordCount = false
ShowRssButtonInSectionTermList = false
UseHugoToc = true
disableSpecial1stPost = true
disableScrollToTop = true
comments = false
hidemeta = true
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "pdmurray.dev"
  # icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "pdmurray.dev"
  subtitle = ""
  imageUrl = "/images/avatar.jpg"
  imageWidth = 240
  imageHeight = 240
  imageTitle = "Peyton Murray"

    # [[params.profileMode.buttons]]
    # name = "Posts"
    # url = "posts"

    # [[params.profileMode.buttons]]
    # name = "Tags"
    # url = "tags"

  # [params.homeInfoParams]
  # Title = "Hi there 👋"
  # Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/peytondmurray"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:peynmurray@gmail.com"

  [[params.socialIcons]]
  name = "cv"
  url = "https://raw.githubusercontent.com/peytondmurray/CV/master/peyton_murray_cv_short.pdf"

  [[params.socialIcons]]
  name = "googlescholar"
  url = "https://scholar.google.com/citations?user=NXE8TDYAAAAJ&hl=en"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/peytondm/"

  [[params.socialIcons]]
  name = "orcid"
  url = "https://orcid.org/0000-0003-0389-0611"

  [[params.socialIcons]]
  name = "researchgate"
  url = "https://researchgate.net/profile/Peyton_Murray"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  # [params.editPost]
  # URL = "https://github.com/<path_to_repo>/content"
  # Text = "Suggest Changes"
  # appendFilePath = true

  # [params.fuseOpts]
  # isCaseSensitive = false
  # shouldSort = true
  # location = 0
  # distance = 1_000
  # threshold = 0.4
  # minMatchCharLength = 0
  # limit = 10
  # keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "research"
name = "research"
url = "/research/"
weight = 20

[markup.highlight]
noClasses = false

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
  [markup.goldmark.renderer]
    unsafe = true
