version: 2.1

orbs:
    node: circleci/node@5.0.0

jobs:
    set-credentials:
        docker:
            - image: cimg/node:16.7.0
        steps:
            - checkout
            - run:
                  name: Set github credentials
                  command: |
                      git config user.email "circleci@circleci"
                      git config user.name "circleci"

workflows:
    deploy:
        jobs:
            - set-credentials
            - node/run:
                  pkg-manager: yarn
                  yarn-run: deploy
                  filters:
                      branches:
                          ignore:
                              - deploy
                  requires:
                      - set-credentials
