# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to GitHub Pages

on:
    push:
        branches: [main]

jobs:
    deploy-gh-pages:
        runs-on: ubuntu-latest
        env:
            TARGET_NODE_VERSION: '16'
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ env.TARGET_NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.TARGET_NODE_VERSION }}
                  cache: 'yarn'
            - name: Publish website
              run: |
                  # abort on errors
                  set -e

                  # build
                  yarn build

                  # navigate into the build output directory
                  cd dist

                  git init
                  git checkout -b deploy
                  git add -A
                  git commit -nm 'deploy'

                  git push -f git@github.com:peytondmurray/peytondmurray.github.io.git deploy

                  cd -
